<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                'name' => 'iPhone 14 Pro',
                'sku' => 'IPH14PRO',
                'price' => 1099.99,
                'discount_price' => 999.99,
                'image' => 'https://via.placeholder.com/300x300?text=iPhone+14+Pro',
                'description' => 'Apple iPhone 14 Pro with A16 Bionic chip, 6.1-inch display, 48MP main camera.',
                'platform' => 'ios',
                'stock' => 20,
                'is_featured' => true,
                'is_active' => true,
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 13',
                'sku' => 'IPH13',
                'price' => 799.99,
                'discount_price' => 749.99,
                'image' => 'https://via.placeholder.com/300x300?text=iPhone+13',
                'description' => 'Apple iPhone 13 with A15 Bionic chip, 6.1-inch display, Dual 12MP cameras.',
                'platform' => 'ios',
                'stock' => 15,
                'is_featured' => false,
                'is_active' => true,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 12',
                'sku' => 'IPH12',
                'price' => 699.99,
                'discount_price' => 649.99,
                'image' => 'https://via.placeholder.com/300x300?text=iPhone+12',
                'description' => 'Apple iPhone 12 with A14 Bionic chip, 6.1-inch display, 5G support.',
                'platform' => 'ios',
                'stock' => 12,
                'is_featured' => false,
                'is_active' => true,
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 14',
                'sku' => 'IPH14',
                'price' => 899.99,
                'discount_price' => 799.99,
                'image' => 'https://via.placeholder.com/300x300?text=iPhone+14',
                'description' => 'Apple iPhone 14 with A15 Bionic chip, 6.1-inch display, Dual 12MP cameras.',
                'platform' => 'ios',
                'stock' => 18,
                'is_featured' => true,
                'is_active' => true,
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 15',
                'sku' => 'IPH15',
                'price' => 999.99,
                'discount_price' => 949.99,
                'image' => 'https://via.placeholder.com/300x300?text=iPhone+15',
                'description' => 'Apple iPhone 15 with A17 Pro chip, 6.1-inch display, Advanced dual-camera system.',
                'platform' => 'ios',
                'stock' => 25,
                'is_featured' => true,
                'is_active' => true,
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 11',
                'sku' => 'IPH11',
                'price' => 599.99,
                'discount_price' => 549.99,
                'image' => 'https://via.placeholder.com/300x300?text=iPhone+11',
                'description' => 'Apple iPhone 11 with A13 Bionic chip, 6.1-inch display, Dual camera system.',
                'platform' => 'ios',
                'stock' => 8,
                'is_featured' => false,
                'is_active' => true,
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPad Air',
                'sku' => 'IPAD-AIR',
                'price' => 599.99,
                'discount_price' => 549.99,
                'image' => 'https://via.placeholder.com/300x300?text=iPad+Air',
                'description' => 'Apple iPad Air with M1 chip, 10.9-inch display, Magic Keyboard support.',
                'platform' => 'ios',
                'stock' => 14,
                'is_featured' => false,
                'is_active' => true,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone SE',
                'sku' => 'IPHONE-SE',
                'price' => 429.99,
                'discount_price' => 399.99,
                'image' => 'https://via.placeholder.com/300x300?text=iPhone+SE',
                'description' => 'Apple iPhone SE with A15 Bionic, 4.7-inch display, 5G capable.',
                'platform' => 'ios',
                'stock' => 10,
                'is_featured' => false,
                'is_active' => true,
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Samsung Galaxy S23',
                'sku' => 'SGS23',
                'price' => 999.99,
                'discount_price' => 899.99,
                'image' => 'https://via.placeholder.com/300x300?text=Galaxy+S23',
                'description' => 'Samsung Galaxy S23 with Snapdragon 8 Gen 2, 6.1-inch display, 50MP camera.',
                'platform' => 'android',
                'stock' => 25,
                'is_featured' => true,
                'is_active' => true,
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Google Pixel 7',
                'sku' => 'PIX7',
                'price' => 699.99,
                'discount_price' => 649.99,
                'image' => 'https://via.placeholder.com/300x300?text=Pixel+7',
                'description' => 'Google Pixel 7 with Google Tensor chip, 6.3-inch display, Night Sight mode.',
                'platform' => 'android',
                'stock' => 18,
                'is_featured' => false,
                'is_active' => true,
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Samsung Galaxy A53',
                'sku' => 'SGA53',
                'price' => 449.99,
                'discount_price' => 399.99,
                'image' => 'https://via.placeholder.com/300x300?text=Galaxy+A53',
                'description' => 'Samsung Galaxy A53 with Exynos 1280, 6.5-inch display, 64MP main camera.',
                'platform' => 'android',
                'stock' => 22,
                'is_featured' => false,
                'is_active' => true,
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'OnePlus 11',
                'sku' => 'OP11',
                'price' => 699.99,
                'discount_price' => 649.99,
                'image' => 'https://via.placeholder.com/300x300?text=OnePlus+11',
                'description' => 'OnePlus 11 with Snapdragon 8 Gen 2, 6.7-inch AMOLED display, Hasselblad camera.',
                'platform' => 'android',
                'stock' => 16,
                'is_featured' => true,
                'is_active' => true,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Google Pixel 8',
                'sku' => 'PIX8',
                'price' => 799.99,
                'discount_price' => 749.99,
                'image' => 'https://via.placeholder.com/300x300?text=Pixel+8',
                'description' => 'Google Pixel 8 with Tensor G3, 6.2-inch display, AI-powered camera features.',
                'platform' => 'android',
                'stock' => 20,
                'is_featured' => true,
                'is_active' => true,
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Samsung Galaxy Z Fold5',
                'sku' => 'SGZF5',
                'price' => 1799.99,
                'discount_price' => 1699.99,
                'image' => 'https://via.placeholder.com/300x300?text=Galaxy+Z+Fold5',
                'description' => 'Samsung Galaxy Z Fold5 with Snapdragon 8 Gen 2, Foldable display, S Pen included.',
                'platform' => 'android',
                'stock' => 8,
                'is_featured' => true,
                'is_active' => true,
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Motorola Edge 40',
                'sku' => 'MTE40',
                'price' => 549.99,
                'discount_price' => 499.99,
                'image' => 'https://via.placeholder.com/300x300?text=Edge+40',
                'description' => 'Motorola Edge 40 with Snapdragon 8 Gen 1, 6.6-inch display, 50MP camera.',
                'platform' => 'android',
                'stock' => 12,
                'is_featured' => false,
                'is_active' => true,
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nothing Phone 1',
                'sku' => 'NPH1',
                'price' => 399.99,
                'discount_price' => 349.99,
                'image' => 'https://via.placeholder.com/300x300?text=Nothing+Phone+1',
                'description' => 'Nothing Phone 1 with Snapdragon 778+, 6.55-inch AMOLED, Unique glyph design.',
                'platform' => 'android',
                'stock' => 14,
                'is_featured' => false,
                'is_active' => true,
                'rating' => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
